### ISSUE TITLE
LimitTo handling unknown values

### ISSUE THREAD

**Issue by Subtixx** [maartendecat/icndb-api#10]
```
<br />
<b>Notice</b>:  Undefined index:  in <b>/home/alumni/mdecat/chuck/api-github/classes/ChuckDatabase.inc.php</b> on line <b>124</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function replaceNames() on null in /home/alumni/mdecat/chuck/api-github/classes/ChuckAPI.inc.php:220
Stack trace:
#0 /home/alumni/mdecat/chuck/api-github/api.php(78): ChuckAPI-&gt;echoRandomQuoteBelongingTo('Chuck', 'Norris', Array)
#1 {main}
  thrown in <b>/home/alumni/mdecat/chuck/api-github/classes/ChuckAPI.inc.php</b> on line <b>220</b><br />
```

When using some string in limitTo and it's not found maybe?:
http://api.icndb.com/jokes/random?limitTo=[test]

**Comment by irkfdb** [comment]
Hey @maartendecat , we can do check whether category exists in the system before doing the lookup, how do you think such request should be handled - when provided category does not exist ?
* return any random quote from the database
* return some clean witty dialogue of chuck norris - when category provided does not exist
