### ISSUE TITLE
API doesn't provide CORS header ‘Access-Control-Allow-Origin’

### ISSUE THREAD

**Issue by GK-Hynes** [maartendecat/icndb-api#18]
I recently made use of your fantastic API on a small site built to practice working with APIs. It worked fine on my local development environment but when I pushed it to GitHub pages I ran into the problem that the API doesn't have an ‘Access-Control-Allow-Origin’ CORS header, making it tricky to call from a site via JavaScript. I've tried using [crossorigin.me](https://corsproxy.github.io/) and [cors.io](https://cors.io/) with limited success. Would it be possible to add the header to the API in a future build?

Error on Firefox Developer Edition Version 62.0b4 (64-bit):
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://crossorigin.me/https://api.icndb.com/jokes/random/5. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by maartendecat** [comment]
Hi there,

That header has been present for a while:

![image](https://user-images.githubusercontent.com/1494225/42149187-7826795a-7dd5-11e8-819d-fef61dbd1328.png)

Haven't tested it with Firefox, but should work too. Can you doublecheck on your side?

**Comment by GK-Hynes** [comment]
Thank you for taking the time to respond. I've reverted to an older version of my project and it's now inexplicably working on Firefox. I'm not sure what was going wrong. I'll keep an eye on it and see if I run into any more problems. 

Thanks again for the great API.
