### ISSUE TITLE
JavaScript escaping is wrong

### ISSUE THREAD

**Issue by SimenB** [maartendecat/icndb-api#2]
E.g. `http://api.icndb.com/jokes/537?escape=javascript`
It escapes `'`, which is wrong.

I do not know any PHP, so I can't provide a PR, but I found this http://www.pontikis.net/tip/?id=5

EDIT: For anyone finding this, and using JavaScript
```js
JSON.parse(response.replace(/\\'/g, '\''));
```

**Comment by maartendecat** [comment]
Hi,

I just pushed an update: JavaScript escaping indeed escaped too much. It should be fixed now, can you verify?

Regards and thanks for reporting

**Comment by SimenB** [comment]
Yup, works fine now. Thanks!
